language: rust

rust:
  - stable
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-D warnings"

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

install:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt -- --check
  - cargo clippy --all-targets -- -D clippy::all
  - cargo build
  - cargo test -- --show-output
